### ISSUE TITLE
Konstigt variabelnamn, "is" insinuerar att det skulle vara en bool.

### ISSUE THREAD

**Issue by glajan** [adilyakut/Modul3-BalloonPopping#1]
https://github.com/adilyakut/Modul3-BalloonPopping/blob/f2c4eab1287b4c9406fd32aa0738060b81378189/app.js#L1

**Comment by glajan** [comment]
Du använder inte den variabeln alls faktiskt.

**Comment by adilyakut** [comment]
variable names updated!
